### ISSUE TITLE
What's up with the grid.css file

### ISSUE THREAD

**Issue by jud3bl4nk** [jud3bl4nk/ecommerce-pattern-library#2]
Hi,
As discussed:  grid.css isn't linking to my cards library and I'm not sure why. The Buttons library is linking up just fine, so I assume it's a simple error in my code, but I don't see the problem (as per usual). Let me know what you find!
Thanks,
Jude
@mackenzierose

**Comment by MacKenzieRose** [comment]
Hey @jud3bl4nk 

So I've played with the files, and the good news is that grid.css IS working! We just need to tweak the code a little bit to see it. 

In dino.html:
The first big thing in this file is that we need to put the "img-flex" class on your image. I would also recommend putting sizes on your second unit (line 5).

In cards.css:
We don't need to include any display or grid values in this code, because grid.css does all of this for us already. The only code you need to keep in this file (from what you currently have) is:

.card {
  background-color: #fff;
}

I also added "border: 1px solid black;" so I could see the edges of your card. 


Let me know how these changes go for you.

Cheers!

MacKenzie

**Comment by jud3bl4nk** [comment]
Thanks; you are a gentleman and a scholar <3
 I have several other questions for you but, I'll tag them as new issues.
Cheers!
